version: '3'
services:
  # Development database
  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=invois
      - POSTGRES_USER=invois
      - POSTGRES_PASSWORD=invois
    volumes:
      - invois-postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - invois-bridge

networks:
  invois-bridge:
    external: true

volumes:
  invois-postgresql:
