version: "3"
services:
  api-service:
    build:
      context: ../../api/
      dockerfile: Dockerfile
      args:
        - DEPLOY_MODE=local_docker
    environment:
      - APP_ENV=local_docker
    networks:
      - invois-bridge
    ports:
      - "9090:9090"

networks:
  invois-bridge:
    external: true
