export enum Icons {
  X = 'x',
  ALERT_CIRCLE = 'alert-circle',
  BELL = 'bell',
  SEARCH = 'search',
  HOME = 'home',
  USER = 'user',
  SUITCASE = 'suitcase',
  FILE = 'file',
  TIME = 'time',
  DOLLAR_CIRCLE = 'dollar-circle',
  GOOGLE = 'google',
  FACEBOOK = 'facebook',
  LINKEDIN = 'linkedin',
  EDIT = 'edit',
  TRASH = 'trash',
  PLUS = 'plus',
  MORE = 'more',
}
